#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#

homePage:
    path: /
    defaults: { _controller: AppBundle:Home:index}

product:
    path: /product
    defaults: { _controller: AppBundle:Product:index}

admin:
   path: /admin
   defaults: { _controller: AppBundle:Admin:index}